baseURL = "/"
languageCode = "en-au"
title = "HaskellGuide.com"
theme = "kube"
description = "Usage of basic Haskell functionality dramatically improves software engineering quality but when people and companies start the journey they often find what's being discussed on social media and blogged about is astronaut territory. HaskellGuide.com fixes that. We provide practial guidance on how to use Haskell in the industry and module based learning that teaches you how to optimise for approachable codebases that are easy to understand and work with."
Paginate = 286
[Params]
  RSSLink = "/rss"
  author = "geoffreyhuntley"
  github = "haskellguide" 
  twitter = "geoffreyhuntley"
  email = "ghuntley@ghuntley.com"

[[menu.main]]
    name = "Learn Haskell"
    weight = -200
    url = "/learn/"
[[menu.main]]
    name = "Guidance"
    weight = -100
    url = "/guides/"
[[menu.main]]
    name = "State of the Ecosystem"
    weight = -50
    url = "https://github.com/Gabriel439/post-rfc/blob/master/sotu.md"
[[menu.main]]
    name = "Anthology"
    weight = 0
    url = "/anthology/"
